### PR TITLE
Ignore gradle wrapper binary artifacts

### LINKED ISSUE #6: Can we configure to ignore gradle-wrapper.jar binary artifacts?
Related:
* https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10425
* https://github.com/ossf/allstar/pull/176
* https://github.com/ossf/allstar/issues/242#issuecomment-1194641312

### PR DESCRIPTION
**Pull request by trask**
Resolves #6

### CODE REVIEW

**Review by breedx-splk — APPROVED** [review]
Yeah, we really need this. It's currently quite aggressive, for example [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10425).

**Review by pellared — COMMENTED** [review]
Such configuration should be on repo level.

**Comment by trask** [comment]
how do we do that?

was just following Google's practice: https://github.com/google/allstar-config/blob/main/binary_artifacts.yaml#L5-L6

**Comment by trask** [comment]
> was just following Google's practice: https://github.com/google/allstar-config/blob/main/binary_artifacts.yaml#L5-L6

btw, this was the fix recommended by @jeffmendoza from @ossf in https://github.com/open-telemetry/.allstar/issues/6#issuecomment-1932735031

**Comment by sakshi-1505** [comment]
> how do we do that?
> 
> was just following Google's practice: https://github.com/google/allstar-config/blob/main/binary_artifacts.yaml#L5-L6

I can raise a PR to implement repo level ignores but is `gradle-wrapper` binary a must required thing for java projects; if yes then we can have at org level or so?

**Review by pellared — APPROVED** [review]
I see that there are more Java repos than I expected: https://github.com/open-telemetry?q=java&type=all&language=&sort=

**Review by arminru — APPROVED** [review]

**Comment by trask** [comment]
hm, Allstar is now saying we are in compliance even before merging this...

https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10425#issuecomment-1936697919

**Comment by trask** [comment]
Nevermind, Allstar changed its mind and re-opened it: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10425#issuecomment-1936703974

**Review by sakshi-1505 — APPROVED** [review]

**Review by jpkrohling — APPROVED** [review]

**Pull request merged**
